version: '3.8'
services:
  app:
    build: . # Build image từ Dockerfile trong thư mục hiện tại
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=identity_service;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: #password
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y" # Chấp nhận EULA
      SA_PASSWORD: phuc819615 # Đặt mật khẩu mạnh
      MSSQL_PID: "Express" # Sử dụng phiên bản Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
